### ISSUE TITLE
Set up Testing Libraries

### ISSUE THREAD

**Issue by dgd03146** [dgd03146/imgeozi#9]
## 📌 Issue

- Set up Testing lIbraries.

<br/>

## ☑️ To-do

- [x] Set up React Testing Library
- [x] Set up Jest
- [x] Set up PlayWright
- [x] Set up Vitest
